### ISSUE TITLE
export 'RuntimeCompiler' was not found in '@angular/compiler'

### ISSUE THREAD

**Issue by HFTSOL** [laco0416/ng-dynamic#10]
I've been using your module in my app for a bit, and it's bee working magnificently!  Unfortunately, the time came to upgrade to the latest Angular-CLI, and so the battle began.  I went from beta 22.1 to beta 28.3, and spent about 2 hours (post update) fixing the things that it changed or broke in my app; but now it's working again.  That being said, it is giving me a warning about your module, but I can't see that it's breaking anything.

```
WARNING in ./~/ng-dynamic/src/dynamic-component/module.js
27:52-67 "export 'RuntimeCompiler' was not found in '@angular/compiler'
```

Currently using version 1.1.0 ng-dynamic.

Any ideas?

**Comment by zwolej** [comment]
Fast workaround is to use "--aot false" flag in your ng commands. From what I have experienced it is failing since aot is enabled as default in angular cli.

**Comment by HFTSOL** [comment]
So I would need to disable AoT for the entire application just to allow your module to use the JiT compiler?

**Comment by zwolej** [comment]
Thats only temporary quick solution

**Comment by HFTSOL** [comment]
Ok, I'm with you.  Since it's not breaking anything for me, I'm find for now.  If things change, I'll try it.

In the mean time, if you need me to test anything or try something to help fix or improve your module, just let me know.

**Comment by lacolaco** [comment]
`RuntimeCompiler` is renamed to `JitCompiler` since Angular 2.3, and ng-dynamic 2.x works with that.

See https://github.com/laco0416/ng-dynamic/issues/6

**Comment by HFTSOL** [comment]
That did it.  I updated to version 2.0.0, and the warning is gone.  Thanks boss!

**Comment by leocaseiro** [comment]
Hi @laco0416, 
I'm sorry posting on this closed issue, but I was wondering why is not possible to work with AOT?What should be done to make it working with AOT? Has anything changed since 4.x release?

>UPDATE: I found this approach https://github.com/laco0416/ng-dynamic/issues/3#issuecomment-278450789 and I'm going to test with the current 4.x

I believe AOT improves performance and I would like to keep using in my app.

Thanks!
