### ISSUE TITLE
Support for ng4

### ISSUE THREAD

**Issue by lacolaco** [laco0416/ng-dynamic#14]
As far as I think, no changes break this library's code in 4.0. so I try to support 2.4 **and** 4.0 both version.

**Comment by lacolaco** [comment]
blocked by https://github.com/angular/angular/issues/15510

**Comment by richardsengers** [comment]
Lets pray this gets fixed soon!

**Comment by lacolaco** [comment]
I've just published ng-dynamic@3.0.0 for v4. Sorry for late!
