### ISSUE TITLE
Module not found: Error: Can't resolve '@angular/compiler/src/jit/compiler'

### ISSUE THREAD

**Issue by kambbado** [laco0416/ng-dynamic#15]
I'm using ng-dynamic v. 2.0.1, when is run "ng build -prod", I get the error below.  Any suggestions?

> ERROR in ./src/$$_gendir/app/login/login.module.ngfactory.ts
Module not found: Error: Can't resolve '@angular/compiler/src/jit/compiler' in 'D:\Dashboard\Web\src\$$_gendir\app\login'
 @ ./src/$$_gendir/app/login/login.module.ngfactory.ts 80:0-63

My package.json file
> "dependencies": {
    "@angular/animations": "4.0.1",
    "@angular/common": "4.0.1",
    "@angular/compiler": "4.0.1",
    "@angular/core": "4.0.1",
    "@angular/forms": "4.0.1",
    "@angular/http": "4.0.1",
    "@angular/platform-browser": "4.0.1",
    "@angular/platform-browser-dynamic": "4.0.1",
    "@angular/router": "4.0.1",
    "@progress/kendo-angular-buttons": "0.23.0",
    "@progress/kendo-angular-dialog": "0.17.0",
    "@progress/kendo-angular-dropdowns": "0.37.3",
    "@progress/kendo-angular-grid": "0.19.6",
    "@progress/kendo-angular-inputs": "0.19.3",
    "@progress/kendo-angular-intl": "0.11.1",
    "@progress/kendo-angular-l10n": "0.2.1",
    "@progress/kendo-angular-resize-sensor": "0.10.3",
    "@progress/kendo-angular-upload": "0.17.0",
    "@progress/kendo-data-query": "0.5.0",
    "@progress/kendo-theme-default": "2.23.1",
    "@telerik/kendo-theme-bootstrap": "0.10.0",
    "@types/file-saver": "0.0.0",
    "bootstrap": "4.0.0-alpha.6",
    "cldr-data": "30.0.4",
    "core-js": "2.4.1",
    "file-saver": "1.3.3",
    "md2": "0.0.18",
    "minimatch": "3.0.3",
    "moment": "2.18.1",
    "ng-dynamic": "2.0.1",
    "ng2-bootstrap": "1.6.1",
    "ng2-mask": "0.5.2",
    "ng2-webstorage": "1.5.1",
    "rxjs": "5.2.0",
    "ts-helpers": "1.1.2",
    "typescript-collections": "1.2.3",
    "zone.js": "0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "4.0.1",
    "@types/file-saver": "0.0.0",
    "@types/jasmine": "2.5.47",
    "@types/lodash": "4.14.61",
    "@types/node": "7.0.12",
    "codelyzer": "3.0.0-beta.4",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "3.2.0",
    "json-loader": "0.5.4",
    "karma": "1.5.0",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.0.0",
    "karma-jasmine": "1.1.0",
    "protractor": "5.1.1",
    "ts-node": "3.0.2",
    "tslint": "4.5.1",
    "typescript": "2.2.1"
  }

**Comment by hpawe01** [comment]
The package-owner @laco0416 already submitted an issue for this right before you ( #14 ).
He is waiting for the resolving of an angular issue (https://github.com/angular/angular/issues/15510).

**Comment by lacolaco** [comment]
closed (see #14)
