### ISSUE TITLE
How to access context variable?

### ISSUE THREAD

**Issue by ghost** [laco0416/ng-dynamic#2]
Hey,

i include the library as the readme says. How do i access the context? Or how do i pass variables?

`  <div *dynamicComponent="template; context: {text: text};"></div>`

**Comment by AliNm14** [comment]
@DeroSavage  did you find a solution?

**Comment by lacolaco** [comment]
Hi @DeroSavage. Please see this demo. 
https://github.com/laco0416/ng-dynamic/blob/master/demo/src/dynamic-cmp-demo.component.ts#L26-L34
