### ISSUE TITLE
@angular/compiler/index"' has no exported member 'RuntimeCompiler'

### ISSUE THREAD

**Issue by aliry** [laco0416/ng-dynamic#6]
looks like latest Angular version (2.4.2) compiler API does not have "RuntimeCompiler" anymore.

**Comment by arm5472** [comment]
This is unfortunate. The trend suggests that the angular team are dead against in-browser compilation. It's such an important factor in my project, so I've switched to RiotJS.

**Comment by aliry** [comment]
looks like they are introducing new concept to support AOT compilation.
call JitCompiler.compileModuleAndAllComponentsAsync(runtimeModule) to get the componentFactory

I'm trying to figure how exactly this works!

**Comment by lacolaco** [comment]
since 2.3.0, `RuntimeCompiler` was renamed to `JitCompiler` .

**Comment by lacolaco** [comment]
I'll update ng-dynamic for Angular 2.4, and the update is incompatible with <2.2 versions.

**Comment by lacolaco** [comment]
working at https://github.com/laco0416/ng-dynamic/pull/7

**Comment by lacolaco** [comment]
I just published ng-dynamic@2.0.0 for Angular 2.3+. Thanks for feedbacks!
